/**
  ********************************************************************************
  * @brief   ΤΙ F28337S Sine Wave Generator
  * @date    Jul 2016
  * @version 1.0
  * @author  George Christidis
  ********************************************************************************
  * @details
			This program uses a DAC to output a sinusoidal wave 0-3V, 50Hz. The
			sine function is computed using the Trigonometric Math Unit. The DAC
			is triggered by an interrupt, generated by the EPWM3 peripheral.
	******************************************************************************
	*/

#include "F28x_Project.h"

__interrupt void scia_rx_isr(void);
void InitPWM3(void), InitDAC(void);
__interrupt void epwm3_isr(void)

void main(void)
{
	//------- INTERNAL INIT------------//
    InitSysCtrl();
    DINT; //Disable CPU interrupts
    InitPieCtrl();
    IER = 0x0000; //Disable CPU interrupts and clear all CPU interrupt flags:
    IFR = 0x0000;
    InitPieVectTable();
    //------- END INTERNAL INIT--------//

	InitPWM3();
	InitDAC();

    while(1)
    {

    }
}

__interrupt void epwm3_isr(void)
{
    static int daccounter=0;
    float wt, sinwt;
    uint16_t dacoutv;

    if (daccounter<1000) daccounter++; else daccounter=0;
    wt = daccounter / 1000.0F;
    sinwt = __sinpuf32(wt);
    dacoutv = (sinwt + 1.0F) * 4095.0F / 2.0F;
    DacaRegs.DACVALS.bit.DACVALS = dacoutv;

    EPwm3Regs.ETCLR.bit.INT = 1; //Clear INT flag for this timer
    PieCtrlRegs.PIEACK.all = PIEACK_GROUP3; //Acknowledge this interrupt to receive more interrupts from group 3
}

void InitPWM3(void)
{
    EALLOW;
    //PWMFeq=100MHz
    CpuSysRegs.PCLKCR2.bit.EPWM3=1; 			//Disable Clock Gating
    EPwm3Regs.TBCTL.bit.CTRMODE = 00; 			//Up count mode
    EPwm3Regs.TBCTL.bit.HSPCLKDIV = 0x0;		//Clock ratio to SYSCLKOUT
    EPwm3Regs.TBCTL.bit.CLKDIV = 0x0;
    EPwm3Regs.TBPRD = 1999; 					//freq=50kHz
    EPwm3Regs.ETSEL.bit.INTSEL = ET_CTR_ZERO;	//Select INT on Zero event
    EPwm3Regs.ETSEL.bit.INTEN = 1;				//Enable INT
    EPwm3Regs.ETPS.bit.INTPRD = ET_1ST;         //Generate INT on 1st event
    PieVectTable.EPWM3_INT = &epwm3_isr;
    IER |= M_INT3; 								//Enable CPU INT3 which is connected to EPWM1-3 INT:
    PieCtrlRegs.PIEIER3.bit.INTx3 = 1;			//Interrupt Enable for INT3.7
    EINT;  										//Enable Global interrupt INTM
    ERTM;  										//Enable Global realtime interrupt DBGM
    CpuSysRegs.PCLKCR0.bit.TBCLKSYNC = 1; 		//start PWM counters
    EDIS;
}
void InitDAC(void)
{
	//pin 27 on board//
    EALLOW;
    DacaRegs.DACCTL.bit.SYNCSEL = 2; 	//PWMSYNC3
    DacaRegs.DACCTL.bit.DACREFSEL = 1; 	//ADC VREFHI/VREFLO are the reference voltages
    DacaRegs.DACVALS.bit.DACVALS = 0; 	//init with 0V
    DacaRegs.DACOUTEN.bit.DACOUTEN = 1; //Enable DAC
    EDIS;
}
